"""Build a runnable 3D circular-pipe OpenFOAM multi-species case.

The generated case is a local shutdown review case, not the 12 km full-pipe
solver.  It uses OpenFOAM's compressible reacting-flow field layout with
chemistry and combustion disabled:

* 3D circular pipe mesh from blockMesh.
* H2/O2/N2 mass-fraction fields mapped from the 1D H2/N2/Air mole fractions.
* Closed inlet/outlet and no-slip pipe wall for shutdown stratification review.
* Gravity enabled.

Air from the 1D model is split into O2 and N2 before writing OpenFOAM fields.
"""

from __future__ import annotations

import argparse
import math
import shutil
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from h2purge.constants import M_H2, M_N2

M_O2 = 31.998e-3

HEADER = r"""/*--------------------------------*- C++ -*----------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     |                                                 |
|   \\  /    A nd           | Generated by hydrogen_purge_sim                 |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
"""


def write_text(path: Path, text: str) -> None:
    """Write OpenFOAM dictionaries/scripts with Unix line endings."""

    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def foam_header(cls: str, obj: str, location: str = '"0"') -> str:
    return (
        HEADER
        + f"""FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    location    {location};
    object      {obj};
}}
// ************************************************************************* //
"""
    )


def dict_header(obj: str, location: str = '"system"') -> str:
    return foam_header("dictionary", obj, location)


def load_local_profile(case_id: str, window: str) -> pd.DataFrame:
    path = ROOT / "cfd_cases" / case_id / "windows" / window / "initial_1d_profile.csv"
    if not path.exists():
        raise FileNotFoundError(path)
    df = pd.read_csv(path)
    need = {"x_local_m", "x_H2_molfrac", "x_N2_molfrac", "x_Air_molfrac"}
    missing = need.difference(df.columns)
    if missing:
        raise ValueError(f"{path} missing columns: {sorted(missing)}")
    return df


def select_window(df: pd.DataFrame, length_m: float) -> pd.DataFrame:
    """Select a centered local segment around the strongest H2 gradient."""

    x = df["x_local_m"].to_numpy(dtype=float)
    h2 = df["x_H2_molfrac"].to_numpy(dtype=float)
    grad = np.abs(np.gradient(h2, x))
    center = float(x[int(np.argmax(grad))])
    start = max(float(x.min()), center - 0.5 * length_m)
    end = min(float(x.max()), start + length_m)
    start = max(float(x.min()), end - length_m)
    out = df[(df["x_local_m"] >= start) & (df["x_local_m"] <= end)].copy()
    out["x_case_m"] = out["x_local_m"] - start
    return out


def mole_to_mass(h2: np.ndarray, n2_raw: np.ndarray, air: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    x_h2 = np.clip(h2, 0.0, 1.0)
    x_o2 = np.clip(0.21 * air, 0.0, 1.0)
    x_n2 = np.clip(n2_raw + 0.79 * air, 0.0, 1.0)
    total = np.maximum(x_h2 + x_o2 + x_n2, 1.0e-14)
    x_h2, x_o2, x_n2 = x_h2 / total, x_o2 / total, x_n2 / total
    denom = np.maximum(x_h2 * M_H2 + x_o2 * M_O2 + x_n2 * M_N2, 1.0e-14)
    y_h2 = x_h2 * M_H2 / denom
    y_o2 = x_o2 * M_O2 / denom
    y_n2 = x_n2 * M_N2 / denom
    y_sum = np.maximum(y_h2 + y_o2 + y_n2, 1.0e-14)
    return y_h2 / y_sum, y_o2 / y_sum, y_n2 / y_sum


def cell_x_centres(length_m: float, nx: int, ny: int, nz: int) -> np.ndarray:
    x_centres = (np.arange(nx) + 0.5) * length_m / nx
    values: list[float] = []
    # For a single blockMesh hex block, i is x-fastest, then j, then k.
    for _k in range(nz):
        for _j in range(ny):
            values.extend(x_centres.tolist())
    return np.asarray(values, dtype=float)


def write_block_mesh(path: Path, length_m: float, diameter_m: float, nx: int, ny: int, nz: int) -> None:
    radius = 0.5 * diameter_m
    q = radius / math.sqrt(2.0)
    text = f"""{dict_header("blockMeshDict")}
scale 1;

vertices
(
    (0 {q:.10g} {q:.10g})
    (0 {-q:.10g} {q:.10g})
    (0 {-q:.10g} {-q:.10g})
    (0 {q:.10g} {-q:.10g})
    ({length_m:.10g} {q:.10g} {q:.10g})
    ({length_m:.10g} {-q:.10g} {q:.10g})
    ({length_m:.10g} {-q:.10g} {-q:.10g})
    ({length_m:.10g} {q:.10g} {-q:.10g})
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges
(
    arc 0 1 (0 0 {radius:.10g})
    arc 1 2 (0 {-radius:.10g} 0)
    arc 2 3 (0 0 {-radius:.10g})
    arc 3 0 (0 {radius:.10g} 0)
    arc 4 5 ({length_m:.10g} 0 {radius:.10g})
    arc 5 6 ({length_m:.10g} {-radius:.10g} 0)
    arc 6 7 ({length_m:.10g} 0 {-radius:.10g})
    arc 7 4 ({length_m:.10g} {radius:.10g} 0)
);

boundary
(
    inlet
    {{
        type wall;
        faces
        (
            (0 3 2 1)
        );
    }}
    outlet
    {{
        type wall;
        faces
        (
            (4 5 6 7)
        );
    }}
    pipeWall
    {{
        type wall;
        faces
        (
            (0 1 5 4)
            (1 2 6 5)
            (2 3 7 6)
            (3 0 4 7)
        );
    }}
);

mergePatchPairs
(
);
"""
    write_text(path, text)


def scalar_values(values: np.ndarray) -> str:
    body = "\n".join(f"{float(v):.10g}" for v in values)
    return f"nonuniform List<scalar>\n{len(values)}\n(\n{body}\n)\n;"


def write_species(path: Path, name: str, values: np.ndarray) -> None:
    text = f"""{foam_header("volScalarField", name)}
dimensions      [0 0 0 0 0 0 0];
internalField   {scalar_values(values)}

boundaryField
{{
    inlet
    {{
        type            zeroGradient;
    }}
    outlet
    {{
        type            zeroGradient;
    }}
    pipeWall
    {{
        type            zeroGradient;
    }}
}}
"""
    write_text(path, text)


def write_uniform_scalar(path: Path, name: str, dimensions: str, value: float, wall_type: str = "zeroGradient") -> None:
    text = f"""{foam_header("volScalarField", name)}
dimensions      {dimensions};
internalField   uniform {value:.10g};

boundaryField
{{
    inlet
    {{
        type            {wall_type};
        value           uniform {value:.10g};
    }}
    outlet
    {{
        type            {wall_type};
        value           uniform {value:.10g};
    }}
    pipeWall
    {{
        type            {wall_type};
        value           uniform {value:.10g};
    }}
}}
"""
    write_text(path, text)


def write_U(path: Path) -> None:
    text = f"""{foam_header("volVectorField", "U")}
dimensions      [0 1 -1 0 0 0 0];
internalField   uniform (0 0 0);

boundaryField
{{
    inlet
    {{
        type            fixedValue;
        value           uniform (0 0 0);
    }}
    outlet
    {{
        type            fixedValue;
        value           uniform (0 0 0);
    }}
    pipeWall
    {{
        type            fixedValue;
        value           uniform (0 0 0);
    }}
}}
"""
    write_text(path, text)


def write_p(path: Path, p_pa: float) -> None:
    text = f"""{foam_header("volScalarField", "p")}
dimensions      [1 -1 -2 0 0 0 0];
internalField   uniform {p_pa:.10g};

boundaryField
{{
    inlet
    {{
        type            zeroGradient;
    }}
    outlet
    {{
        type            zeroGradient;
    }}
    pipeWall
    {{
        type            zeroGradient;
    }}
}}
"""
    write_text(path, text)


def write_control(path: Path, end_time: float, dt: float) -> None:
    text = f"""{dict_header("controlDict")}
application     rhoReactingFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {end_time:g};
deltaT          {dt:g};
writeControl    adjustable;
writeInterval   {max(end_time / 5.0, dt):g};
purgeWrite      0;
writeFormat     ascii;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   8;
runTimeModifiable true;
adjustTimeStep  yes;
maxCo           0.4;
maxDeltaT       {dt:g};
"""
    write_text(path, text)


def write_g(path: Path) -> None:
    text = f"""{foam_header("uniformDimensionedVectorField", "g", '"constant"')}
dimensions      [0 1 -2 0 0 0 0];
value           (0 0 -9.81);
"""
    write_text(path, text)


def write_turbulence(path: Path) -> None:
    text = f"""{dict_header("turbulenceProperties", '"constant"')}
simulationType laminar;
"""
    write_text(path, text)


def copy_reacting_files(case_dir: Path) -> None:
    src = Path("/usr/share/doc/openfoam-examples/examples/combustion/reactingFoam/RAS/chokedNozzle")
    # These files are copied inside WSL by run script when the case is built from Windows.
    note = case_dir / "COPY_TEMPLATE_FILES.txt"
    write_text(
        note,
        "The Python builder creates dictionaries locally.  If thermo files are missing, "
        "run tools/build_openfoam_rho_reacting_pipe_case.py again.\n",
    )


def write_thermo_files(case_dir: Path) -> None:
    """Write minimal links/copies expected by reacting-mixture thermo."""

    template = ROOT / "_missing_openfoam_template"
    # The actual copies are done by a WSL shell step in run script because the
    # tutorial files live under the Linux filesystem.  Keep placeholders here.
    write_text(
        case_dir / "constant" / "thermophysicalProperties",
        """/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by hydrogen_purge_sim                                           |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "constant";
    object      thermophysicalProperties;
}

thermoType
{
    type            heRhoThermo;
    mixture         reactingMixture;
    transport       sutherland;
    thermo          janaf;
    energy          sensibleEnthalpy;
    equationOfState perfectGas;
    specie          specie;
}

inertSpecie N2;

chemistryReader foamChemistryReader;
foamChemistryFile "<constant>/reactionsGRI";
foamChemistryThermoFile "<constant>/thermo.compressibleGasGRI";

dpdt false;
""",
    )
    write_text(
        case_dir / "constant" / "combustionProperties",
        """FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "constant";
    object      combustionProperties;
}
combustionModel none;
active false;
""",
    )
    write_text(
        case_dir / "constant" / "chemistryProperties",
        """FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "constant";
    object      chemistryProperties;
}
chemistryType
{
    chemistrySolver   ode;
    chemistryThermo   psi;
    TDAC              off;
}
initialChemicalTimeStep 1e-07;
chemistry off;
odeCoeffs
{
    solver          Rosenbrock34;
    absTol          1e-12;
    relTol          1e-7;
}
""",
    )
    write_text(
        case_dir / "constant" / "COPY_FROM_OPENFOAM_TEMPLATE.sh",
        """#!/usr/bin/env bash
set -e
src=/usr/share/doc/openfoam-examples/examples/combustion/reactingFoam/RAS/DLR_A_LTS/constant
cp "$src/reactionsGRI" constant/reactionsGRI
cp "$src/thermo.compressibleGasGRI" constant/thermo.compressibleGasGRI
""",
    )


def write_fv_files(case_dir: Path) -> None:
    write_text(
        case_dir / "system" / "fvSchemes",
        f"""{dict_header("fvSchemes")}
ddtSchemes
{{
    default         Euler;
}}
gradSchemes
{{
    default         Gauss linear;
    grad(U)         cellLimited Gauss linear 1;
}}
divSchemes
{{
    default         none;
    div(phi,U)      Gauss limitedLinearV 1;
    div(phi,Yi)     Gauss limitedLinear01 1;
    div(phi,Yi_h)   Gauss limitedLinear 1;
    div(phi,h)      Gauss limitedLinear 1;
    div(phi,K)      Gauss limitedLinear 1;
    div(phid,p)     Gauss limitedLinear 1;
    div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;
}}
laplacianSchemes
{{
    default         Gauss linear corrected;
}}
interpolationSchemes
{{
    default         linear;
}}
snGradSchemes
{{
    default         corrected;
}}
""",
    )
    write_text(
        case_dir / "system" / "fvSolution",
        f"""{dict_header("fvSolution")}
solvers
{{
    "rho.*"
    {{
        solver          diagonal;
    }}
    p
    {{
        solver          GAMG;
        tolerance       1e-07;
        relTol          0.2;
        smoother        GaussSeidel;
        maxIter         120;
        cacheAgglomeration true;
        nCellsInCoarsestLevel 10;
        agglomerator    faceAreaPair;
        mergeLevels     1;
    }}
    pFinal
    {{
        solver          GAMG;
        tolerance       1e-08;
        relTol          0;
        smoother        GaussSeidel;
        maxIter         120;
        cacheAgglomeration true;
        nCellsInCoarsestLevel 10;
        agglomerator    faceAreaPair;
        mergeLevels     1;
    }}
    "(U|h|Yi)"
    {{
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-07;
        relTol          0.1;
    }}
    "(U|h|Yi)Final"
    {{
        solver          PBiCGStab;
        preconditioner  DILU;
        tolerance       1e-08;
        relTol          0;
    }}
}}
PIMPLE
{{
    momentumPredictor yes;
    nOuterCorrectors 1;
    nCorrectors      1;
    nNonOrthogonalCorrectors 1;
}}
relaxationFactors
{{
    equations
    {{
        ".*"            1;
    }}
}}
""",
    )


def write_run_scripts(case_dir: Path) -> None:
    write_text(
        case_dir / "runAll.sh",
        """#!/usr/bin/env bash
set -eo pipefail
export WM_PROJECT_DIR=${WM_PROJECT_DIR:-/usr/share/openfoam}
export FOAM_ETC=${FOAM_ETC:-/usr/share/openfoam/etc}
bash constant/COPY_FROM_OPENFOAM_TEMPLATE.sh
blockMesh > log.blockMesh 2>&1
checkMesh > log.checkMesh 2>&1
rhoReactingFoam > log.rhoReactingFoam 2>&1
foamToVTK > log.foamToVTK 2>&1
""",
    )
    write_text(
        case_dir / "cleanAll.sh",
        """#!/usr/bin/env bash
set -e
rm -rf constant/polyMesh [1-9]* 0.* postProcessing VTK log.*
""",
    )


def write_readme(case_dir: Path, case_id: str, window: str, length_m: float, nx: int, ny: int, nz: int) -> None:
    write_text(
        case_dir / "README.md",
        f"""# OpenFOAM 3D multi-species pipe shutdown case

Source 1D case: `{case_id}`
Source window: `{window}`

This is a runnable local 3D circular-pipe OpenFOAM case for shutdown
stratification review.

Physics included:

- solver: `rhoReactingFoam`;
- compressible perfect-gas multi-species mixture;
- species: H2/O2/N2, with Air split to O2+N2 before writing mass fractions;
- gravity: `(0 0 -9.81)`;
- chemistry/combustion disabled;
- closed inlet/outlet and no-slip pipe wall;
- initial velocity zero.

Mesh:

- local length: {length_m:g} m;
- diameter: 1.2 m;
- cells: {nx} x {ny} x {nz} = {nx * ny * nz}.

Run in WSL/OpenFOAM:

```bash
cd '{case_dir.as_posix()}'
bash runAll.sh
```
""",
    )


def build_case(
    case_id: str,
    window: str,
    out_root: Path,
    length_m: float,
    nx: int,
    ny: int,
    nz: int,
    end_time: float,
    dt: float,
    p_pa: float,
    t_k: float,
) -> Path:
    df_full = load_local_profile(case_id, window)
    df = select_window(df_full, length_m)
    source_x = df["x_case_m"].to_numpy(dtype=float)
    length_actual = float(source_x.max() - source_x.min())
    case_dir = out_root / f"{case_id}_rhoReactingPipe3D"
    if case_dir.exists():
        shutil.rmtree(case_dir)
    for sub in ("0", "constant", "system"):
        (case_dir / sub).mkdir(parents=True, exist_ok=True)

    cell_x = cell_x_centres(length_actual, nx, ny, nz)
    h2_mole = np.interp(cell_x, source_x, df["x_H2_molfrac"].to_numpy(dtype=float))
    n2_mole = np.interp(cell_x, source_x, df["x_N2_molfrac"].to_numpy(dtype=float))
    air_mole = np.interp(cell_x, source_x, df["x_Air_molfrac"].to_numpy(dtype=float))
    y_h2, y_o2, y_n2 = mole_to_mass(h2_mole, n2_mole, air_mole)

    write_block_mesh(case_dir / "system" / "blockMeshDict", length_actual, 1.2, nx, ny, nz)
    write_species(case_dir / "0" / "H2", "H2", y_h2)
    write_species(case_dir / "0" / "O2", "O2", y_o2)
    write_species(case_dir / "0" / "N2", "N2", y_n2)
    write_uniform_scalar(case_dir / "0" / "Ydefault", "Ydefault", "[0 0 0 0 0 0 0]", 0.0)
    write_uniform_scalar(case_dir / "0" / "T", "T", "[0 0 0 1 0 0 0]", t_k, wall_type="zeroGradient")
    write_uniform_scalar(case_dir / "0" / "nut", "nut", "[0 2 -1 0 0 0 0]", 0.0, wall_type="fixedValue")
    write_uniform_scalar(case_dir / "0" / "alphat", "alphat", "[1 -1 -1 0 0 0 0]", 0.0, wall_type="fixedValue")
    write_uniform_scalar(case_dir / "0" / "k", "k", "[0 2 -2 0 0 0 0]", 1.0e-6, wall_type="zeroGradient")
    write_uniform_scalar(case_dir / "0" / "epsilon", "epsilon", "[0 2 -3 0 0 0 0]", 1.0e-6, wall_type="zeroGradient")
    write_U(case_dir / "0" / "U")
    write_p(case_dir / "0" / "p", p_pa)
    write_g(case_dir / "constant" / "g")
    write_turbulence(case_dir / "constant" / "turbulenceProperties")
    write_thermo_files(case_dir)
    write_fv_files(case_dir)
    write_control(case_dir / "system" / "controlDict", end_time, dt)
    write_run_scripts(case_dir)
    write_readme(case_dir, case_id, window, length_actual, nx, ny, nz)

    init = pd.DataFrame(
        {
            "cell_x_m": cell_x,
            "Y_H2": y_h2,
            "Y_O2": y_o2,
            "Y_N2": y_n2,
            "sumY": y_h2 + y_o2 + y_n2,
        }
    )
    init.to_csv(case_dir / "initial_mass_fraction_cells.csv", index=False, encoding="utf-8-sig")
    return case_dir


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--case-id", default="DN1200_u7_p010_stop60")
    parser.add_argument("--window", default="full_isolation_zone_1200m")
    parser.add_argument("--out-root", type=Path, default=ROOT / "openfoam_cases")
    parser.add_argument("--length-m", type=float, default=48.0)
    parser.add_argument("--nx", type=int, default=48)
    parser.add_argument("--ny", type=int, default=12)
    parser.add_argument("--nz", type=int, default=12)
    parser.add_argument("--end-time", type=float, default=30.0)
    parser.add_argument("--dt", type=float, default=0.05)
    parser.add_argument("--p-pa", type=float, default=100000.0)
    parser.add_argument("--t-k", type=float, default=293.15)
    args = parser.parse_args()
    out = build_case(
        args.case_id,
        args.window,
        args.out_root,
        args.length_m,
        args.nx,
        args.ny,
        args.nz,
        args.end_time,
        args.dt,
        args.p_pa,
        args.t_k,
    )
    print(out)


if __name__ == "__main__":
    main()
